apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
spec:
  project: exemplo-project
  source:
    repoURL: https://github.com/Marod12/web-page-deploy
    targetRevision: HEAD
    path: k8s/webcolor
  destination:
    server: https://kubernetes.default.svc
    namespace: webcolor
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: exemplo-project
  namespace: argocd
spec:
  description: Projeto de exemplo para gerenciar aplicações.
  sourceRepos:
    # Lista de repositórios permitidos para este projeto
    - "https://github.com/Marod12/*"
  destinations:
    # Lista de destinos permitidos (clusters e namespaces)
    - namespace: "webcolor"
      server: https://kubernetes.default.svc
