apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
        import /etc/coredns/custom/*.override
    }
    import /etc/coredns/custom/*.server
  NodeHosts: |
    172.27.0.1 host.k3d.internal
    172.27.0.7 k3d-meucluster-agent-2
    172.27.0.8 k3d-meucluster-serverlb
    172.27.0.3 k3d-meucluster-server-1
    172.27.0.5 k3d-meucluster-agent-1
    172.27.0.2 k3d-meucluster-server-0
    172.27.0.6 k3d-meucluster-agent-0
    172.27.0.4 k3d-meucluster-server-2
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    hosts /etc/coredns/NodeHosts {\n      ttl 60\n      reload 15s\n      fallthrough\n    }\n    prometheus :9153\n    forward . 1.1.1.1 8.8.8.8\n    cache 30\n    loop\n    reload\n    loadbalance\n    import /etc/coredns/custom/*.override\n}\nimport /etc/coredns/custom/*.server\n","NodeHosts":"172.27.0.1 host.k3d.internal\n172.27.0.7 k3d-meucluster-agent-2\n172.27.0.8 k3d-meucluster-serverlb\n172.27.0.3 k3d-meucluster-server-1\n172.27.0.5 k3d-meucluster-agent-1\n172.27.0.2 k3d-meucluster-server-0\n172.27.0.6 k3d-meucluster-agent-0\n172.27.0.4 k3d-meucluster-server-2\n"},"kind":"ConfigMap","metadata":{"annotations":{"objectset.rio.cattle.io/applied":"H4sIAAAAAAAA/4yQQa/TMBCE/4q158TUSfsSLHFA74KE4Mipl028aUyc3creFj1V77+jqICQUIHbWOP9NDM3wHP8QrlEYfBwdVBBQEXwN3iWTFNMBB6sP7TmdmRjjKGcJZe7ngmTznedCcPLXS6XgTKTUjFjuhSlbJNABZ8l0AcpWsCD6xrbdHZnnZmlqF3aYCMrZcZ05F9uZ5Y21CtdfoBqPBFr3RzZwWsFS+QAHp6Fp3j6hGeoYCXFnxWQWRQ1CpftKcNXGrWQ2hzFjqiayEZ5EzcGVA99+caU69N1AQ9LW35zrq4yHyOHd+9DEP4ngnHd5hwlU+DyX9/LGcftZtu0Li9Fad2KJxwo/bXUjGUGD8NITd82b/veuW7f4q7tn3A4uN3UTE8dTd2+2e/GQ7dB/4j3MMDr9wAAAP//X3lp4TkCAAA","objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/owner-gvk":"k3s.cattle.io/v1, Kind=Addon","objectset.rio.cattle.io/owner-name":"coredns","objectset.rio.cattle.io/owner-namespace":"kube-system"},"creationTimestamp":"2025-10-18T22:00:20Z","labels":{"objectset.rio.cattle.io/hash":"bce283298811743a0386ab510f2f67ef74240c57"},"name":"coredns","namespace":"kube-system","resourceVersion":"854","uid":"fb57d30e-de97-41db-b50e-4b34025bd4cb"}}
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQQa/TMBCE/4q158TUSfsSLHFA74KE4Mipl028aUyc3creFj1V77+jqICQUIHbWOP9NDM3wHP8QrlEYfBwdVBBQEXwN3iWTFNMBB6sP7TmdmRjjKGcJZe7ngmTznedCcPLXS6XgTKTUjFjuhSlbJNABZ8l0AcpWsCD6xrbdHZnnZmlqF3aYCMrZcZ05F9uZ5Y21CtdfoBqPBFr3RzZwWsFS+QAHp6Fp3j6hGeoYCXFnxWQWRQ1CpftKcNXGrWQ2hzFjqiayEZ5EzcGVA99+caU69N1AQ9LW35zrq4yHyOHd+9DEP4ngnHd5hwlU+DyX9/LGcftZtu0Li9Fad2KJxwo/bXUjGUGD8NITd82b/veuW7f4q7tn3A4uN3UTE8dTd2+2e/GQ7dB/4j3MMDr9wAAAP//X3lp4TkCAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2025-10-18T22:00:20Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "2169"
  uid: fb57d30e-de97-41db-b50e-4b34025bd4cb
