apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source: #Target State
    repoURL: https://github.com/Marod12/devopspro-argo-cd.git
    path: argocd
    targetRevision: HEAD
    # directory:
    #   recurse: true
  destination: #Live State
    namespace: argocd
    server: https://kubernetes.default.svc
