apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source: #Target State
    repoURL: https://github.com/Marod12/web-page-deploy.git
    path: k8s
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'nginx/*'
  destination: #Live State
    namespace: webcolor
    server: https://kubernetes.default.svc
  info:
    - name: Projeto
      value: "Curso de GitOps"
