apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-color-multi-cluster
  namespace: argocd
spec:
  generators:
    - clusters: {}

  template:
    metadata:
      name: 'web-color-{{name}}'
    spec:
      source:
        repoURL: https://github.com/Marod12/web-page-deploy
        path: k8s/webcolor
        targetRevision: HEAD
      destination:
        namespace: 'web-color'
        server: '{{server}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:  
        - CreateNamespace=true
