apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-color-multi-cluster
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: cluster01
            url: https://100.87.137.249:45067
            region: us
            namespace: web-color
          - cluster: cluster02
            url: https://100.87.137.249:43333
            region: br
            namespace: web-color
      
  template:
    metadata:
      name: 'web-color-{{region}}-{{cluster}}'
    spec:
      source:
        repoURL: https://github.com/Marod12/web-page-deploy
        path: k8s/webcolor
        targetRevision: HEAD
      destination:
        namespace: '{{namespace}}'
        server: '{{url}}'
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:  
        - CreateNamespace=true
